// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "PermissionHandlerAppleApi.h"

#if TARGET_OS_OSX
@import FlutterMacOS;
#else
@import Flutter;
#endif

static BOOL __attribute__((unused)) FLTPigeonDeepEquals(id _Nullable a, id _Nullable b) {
  if (a == b) {
    return YES;
  }
  if (a == nil) {
    return b == [NSNull null];
  }
  if (b == nil) {
    return a == [NSNull null];
  }
  if ([a isKindOfClass:[NSNumber class]] && [b isKindOfClass:[NSNumber class]]) {
    return [a isEqual:b] || (isnan([(NSNumber *)a doubleValue]) && isnan([(NSNumber *)b doubleValue]));
  }
  if ([a isKindOfClass:[NSArray class]] && [b isKindOfClass:[NSArray class]]) {
    NSArray *arrayA = (NSArray *)a;
    NSArray *arrayB = (NSArray *)b;
    if (arrayA.count != arrayB.count) {
      return NO;
    }
    for (NSUInteger i = 0; i < arrayA.count; i++) {
      if (!FLTPigeonDeepEquals(arrayA[i], arrayB[i])) {
        return NO;
      }
    }
    return YES;
  }
  if ([a isKindOfClass:[NSDictionary class]] && [b isKindOfClass:[NSDictionary class]]) {
    NSDictionary *dictA = (NSDictionary *)a;
    NSDictionary *dictB = (NSDictionary *)b;
    if (dictA.count != dictB.count) {
      return NO;
    }
    for (id keyA in dictA) {
      id valueA = dictA[keyA];
      BOOL found = NO;
      for (id keyB in dictB) {
        if (FLTPigeonDeepEquals(keyA, keyB)) {
          id valueB = dictB[keyB];
          if (FLTPigeonDeepEquals(valueA, valueB)) {
            found = YES;
            break;
          } else {
            return NO;
          }
        }
      }
      if (!found) {
        return NO;
      }
    }
    return YES;
  }
  return [a isEqual:b];
}

static NSUInteger __attribute__((unused)) FLTPigeonDeepHash(id _Nullable value) {
  if (value == nil || value == (id)[NSNull null]) {
    return 0;
  }
  if ([value isKindOfClass:[NSNumber class]]) {
    NSNumber *n = (NSNumber *)value;
    double d = n.doubleValue;
    if (isnan(d)) {
      // Normalize NaN to a consistent hash.
      return (NSUInteger)0x7FF8000000000000;
    }
    if (d == 0.0) {
      // Normalize -0.0 to 0.0 so they have the same hash code.
      d = 0.0;
    }
    return @(d).hash;
  }
  if ([value isKindOfClass:[NSArray class]]) {
    NSUInteger result = 1;
    for (id item in (NSArray *)value) {
      result = result * 31 + FLTPigeonDeepHash(item);
    }
    return result;
  }
  if ([value isKindOfClass:[NSDictionary class]]) {
    NSUInteger result = 0;
    NSDictionary *dict = (NSDictionary *)value;
    for (id key in dict) {
      result += ((FLTPigeonDeepHash(key) * 31) ^ FLTPigeonDeepHash(dict[key]));
    }
    return result;
  }
  return [value hash];
}

static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface PHPermissionHandlerAppleApiPigeonCodecReader : FlutterStandardReader
@end
@implementation PHPermissionHandlerAppleApiPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface PHPermissionHandlerAppleApiPigeonCodecWriter : FlutterStandardWriter
@end
@implementation PHPermissionHandlerAppleApiPigeonCodecWriter
- (void)writeValue:(id)value {
  {
    [super writeValue:value];
  }
}
@end

@interface PHPermissionHandlerAppleApiPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation PHPermissionHandlerAppleApiPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[PHPermissionHandlerAppleApiPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[PHPermissionHandlerAppleApiPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *PHGetPermissionHandlerAppleApiCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    PHPermissionHandlerAppleApiPigeonCodecReaderWriter *readerWriter = [[PHPermissionHandlerAppleApiPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpPHPermissionHandlerHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PHPermissionHandlerHostApi> *api) {
  SetUpPHPermissionHandlerHostApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpPHPermissionHandlerHostApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PHPermissionHandlerHostApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.permission_handler_apple.PermissionHandlerHostApi.checkPermissionStatus", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:PHGetPermissionHandlerAppleApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(checkPermissionStatusPermission:error:)], @"PHPermissionHandlerHostApi api (%@) doesn't respond to @selector(checkPermissionStatusPermission:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_permission = [GetNullableObjectAtIndex(args, 0) integerValue];
        FlutterError *error;
        NSNumber *output = [api checkPermissionStatusPermission:arg_permission error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.permission_handler_apple.PermissionHandlerHostApi.checkServiceStatus", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:PHGetPermissionHandlerAppleApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(checkServiceStatusPermission:completion:)], @"PHPermissionHandlerHostApi api (%@) doesn't respond to @selector(checkServiceStatusPermission:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_permission = [GetNullableObjectAtIndex(args, 0) integerValue];
        [api checkServiceStatusPermission:arg_permission completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.permission_handler_apple.PermissionHandlerHostApi.requestPermissions", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:PHGetPermissionHandlerAppleApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(requestPermissionsPermissions:completion:)], @"PHPermissionHandlerHostApi api (%@) doesn't respond to @selector(requestPermissionsPermissions:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSArray<NSNumber *> *arg_permissions = GetNullableObjectAtIndex(args, 0);
        [api requestPermissionsPermissions:arg_permissions completion:^(NSDictionary<NSNumber *, NSNumber *> *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.permission_handler_apple.PermissionHandlerHostApi.openAppSettings", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:PHGetPermissionHandlerAppleApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(openAppSettingsWithCompletion:)], @"PHPermissionHandlerHostApi api (%@) doesn't respond to @selector(openAppSettingsWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api openAppSettingsWithCompletion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
