// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

@import Foundation;

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *PHGetPermissionHandlerAppleApiCodec(void);

@protocol PHPermissionHandlerHostApi
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)checkPermissionStatusPermission:(NSInteger)permission error:(FlutterError *_Nullable *_Nonnull)error;
- (void)checkServiceStatusPermission:(NSInteger)permission completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)requestPermissionsPermissions:(NSArray<NSNumber *> *)permissions completion:(void (^)(NSDictionary<NSNumber *, NSNumber *> *_Nullable, FlutterError *_Nullable))completion;
- (void)openAppSettingsWithCompletion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
@end

extern void SetUpPHPermissionHandlerHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PHPermissionHandlerHostApi> *_Nullable api);

extern void SetUpPHPermissionHandlerHostApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PHPermissionHandlerHostApi> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
